In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df

           Entity Code  Year  ny_gdp_pcap_pp_kd
0     Afghanistan  AFG  2000          1617.8264
1     Afghanistan  AFG  2001          1454.1108
2     Afghanistan  AFG  2002          1774.3087
3     Afghanistan  AFG  2003          1815.9282
4     Afghanistan  AFG  2004          1776.9182
...           ...  ...   ...                ...
7058     Zimbabwe  ZWE  2019          3294.8062
7059     Zimbabwe  ZWE  2020          2987.2698
7060     Zimbabwe  ZWE  2021          3184.7854
7061     Zimbabwe  ZWE  2022          3323.1218
7062     Zimbabwe  ZWE  2023          3442.2512

[7063 rows x 4 columns]

In [37]:
df = pd.read_csv("OECD,DF_BLI,+all.csv")

# Tomamos las columnas que nos importan
df = df.drop(columns = [columns for columns in df.columns if columns not in ["LOCATION", "INDICATOR", "OBS_VALUE", "UNIT_MEASURE", "INEQUALITY"]])
df = df[df["INEQUALITY"] == "TOT"]

# Primero el dataframe de life expectancy (HS_LEB), lo limpiamos
life_expectancy = df[df["INDICATOR"] == "HS_LEB"]
print(life_expectancy["UNIT_MEASURE"].unique())  # Es de tipo YR (años)

# Ahora el dataframe de homicide rate (PS_REPH)
homicide_rate = df[df["INDICATOR"] == "PS_REPH"]
print(homicide_rate["UNIT_MEASURE"].unique())  # Es de tipo RATIO 

df

['YR']
['RATIO']

     LOCATION INDICATOR INEQUALITY  OBS_VALUE UNIT_MEASURE
0         AUT   JE_LMIS        TOT        2.3           PC
1         BEL   JE_LMIS        TOT        2.4           PC
2         CAN   JE_LMIS        TOT        3.8           PC
3         CZE   JE_LMIS        TOT        2.3           PC
4         DNK   JE_LMIS        TOT        4.5           PC
...       ...       ...        ...        ...          ...
2360      CRI   HO_NUMR        TOT        1.2        RATIO
2361      CRI   IW_HADI        TOT    16517.0          USD
2362      CRI   EQ_AIRP        TOT       17.5     MICRO_M3
2363      CRI    HS_LEB        TOT       80.5           YR
2366      CRI   PS_REPH        TOT       10.0        RATIO

[935 rows x 5 columns]

In [30]:
life_expectancy

     LOCATION INDICATOR INEQUALITY  OBS_VALUE UNIT_MEASURE
2032      AUS    HS_LEB        TOT       83.0           YR
2033      AUT    HS_LEB        TOT       82.0           YR
2034      BEL    HS_LEB        TOT       82.1           YR
2035      CAN    HS_LEB        TOT       82.1           YR
2036      CZE    HS_LEB        TOT       79.3           YR
2037      DNK    HS_LEB        TOT       81.5           YR
2038      FIN    HS_LEB        TOT       82.1           YR
2039      FRA    HS_LEB        TOT       82.9           YR
2040      DEU    HS_LEB        TOT       81.4           YR
2041      GRC    HS_LEB        TOT       81.7           YR
2042      HUN    HS_LEB        TOT       76.4           YR
2043      ISL    HS_LEB        TOT       83.2           YR
2044      IRL    HS_LEB        TOT       82.8           YR
2045      ITA    HS_LEB        TOT       83.6           YR
2046      JPN    HS_LEB        TOT       84.4           YR
2047      KOR    HS_LEB        TOT       83.3           YR
2048      LUX    HS_LEB        TOT       82.7           YR
2049      MEX    HS_LEB        TOT       75.1           YR
2050      NLD    HS_LEB        TOT       82.2           YR
2051      NZL    HS_LEB        TOT       82.1           YR
2052      NOR    HS_LEB        TOT       83.0           YR
2053      POL    HS_LEB        TOT       78.0           YR
2054      PRT    HS_LEB        TOT       81.8           YR
2055      SVK    HS_LEB        TOT       77.8           YR
2056      ESP    HS_LEB        TOT       83.9           YR
2057      SWE    HS_LEB        TOT       83.2           YR
2058      CHE    HS_LEB        TOT       84.0           YR
2059      TUR    HS_LEB        TOT       78.6           YR
2060      GBR    HS_LEB        TOT       81.3           YR
2061      USA    HS_LEB        TOT       78.9           YR
2062      BRA    HS_LEB        TOT       75.9           YR
2063      CHL    HS_LEB        TOT       80.6           YR
2064      EST    HS_LEB        TOT       78.8           YR
2065      ISR    HS_LEB        TOT       82.9           YR
2066      LVA    HS_LEB        TOT       75.5           YR
2067      RUS    HS_LEB        TOT       73.2           YR
2068      SVN    HS_LEB        TOT       81.6           YR
2069      ZAF    HS_LEB        TOT       64.2           YR
2070     OECD    HS_LEB        TOT       81.0           YR
2348      COL    HS_LEB        TOT       76.7           YR
2349      LTU    HS_LEB        TOT       76.4           YR
2363      CRI    HS_LEB        TOT       80.5           YR

In [31]:
homicide_rate

     LOCATION INDICATOR INEQUALITY  OBS_VALUE UNIT_MEASURE
2150      AUS   PS_REPH        TOT        0.9        RATIO
2151      AUT   PS_REPH        TOT        0.5        RATIO
2152      BEL   PS_REPH        TOT        1.1        RATIO
2153      CAN   PS_REPH        TOT        1.2        RATIO
2154      CZE   PS_REPH        TOT        0.7        RATIO
2155      DNK   PS_REPH        TOT        0.5        RATIO
2156      FIN   PS_REPH        TOT        1.2        RATIO
2157      FRA   PS_REPH        TOT        0.4        RATIO
2158      DEU   PS_REPH        TOT        0.4        RATIO
2159      GRC   PS_REPH        TOT        1.0        RATIO
2160      ISL   PS_REPH        TOT        0.3        RATIO
2161      IRL   PS_REPH        TOT        0.5        RATIO
2162      ITA   PS_REPH        TOT        0.5        RATIO
2163      JPN   PS_REPH        TOT        0.2        RATIO
2164      KOR   PS_REPH        TOT        0.8        RATIO
2165      LUX   PS_REPH        TOT        0.2        RATIO
2166      MEX   PS_REPH        TOT       26.8        RATIO
2167      NLD   PS_REPH        TOT        0.6        RATIO
2168      NZL   PS_REPH        TOT        1.3        RATIO
2169      NOR   PS_REPH        TOT        0.6        RATIO
2170      POL   PS_REPH        TOT        0.5        RATIO
2171      PRT   PS_REPH        TOT        0.7        RATIO
2172      SVK   PS_REPH        TOT        0.8        RATIO
2173      ESP   PS_REPH        TOT        0.7        RATIO
2174      SWE   PS_REPH        TOT        1.1        RATIO
2175      CHE   PS_REPH        TOT        0.3        RATIO
2176      TUR   PS_REPH        TOT        1.0        RATIO
2177      GBR   PS_REPH        TOT        0.2        RATIO
2178      USA   PS_REPH        TOT        6.0        RATIO
2179      BRA   PS_REPH        TOT       19.0        RATIO
2180      CHL   PS_REPH        TOT        2.4        RATIO
2181      EST   PS_REPH        TOT        1.9        RATIO
2182      ISR   PS_REPH        TOT        1.5        RATIO
2183      LVA   PS_REPH        TOT        3.7        RATIO
2184      RUS   PS_REPH        TOT        4.8        RATIO
2185      SVN   PS_REPH        TOT        0.4        RATIO
2186      ZAF   PS_REPH        TOT       13.7        RATIO
2187     OECD   PS_REPH        TOT        2.6        RATIO
2265      HUN   PS_REPH        TOT        0.9        RATIO
2354      COL   PS_REPH        TOT       23.1        RATIO
2355      LTU   PS_REPH        TOT        2.5        RATIO
2366      CRI   PS_REPH        TOT       10.0        RATIO

In [44]:
# Vamos a normalizar los datos

# Primero de life expectancy
min_LE = life_expectancy['OBS_VALUE'].min()
max_LE = life_expectancy['OBS_VALUE'].max()
print(min_LE, max_LE)

life_expectancy_n = (life_expectancy['OBS_VALUE'] - min_LE) / (max_LE - min_LE)

# Ahora para homicide rate
min_HR = homicide_rate['OBS_VALUE'].min()
max_HR = homicide_rate['OBS_VALUE'].max()
print(min_HR, max_HR)

homicide_rate_n = (homicide_rate['OBS_VALUE'] - min_HR) / (max_HR - min_HR)

print(f"life expectancy normalized: max -> {life_expectancy_n.max()}, min -> {life_expectancy_n.min()}, avg -> {life_expectancy_n.mean()}")
print(f"homicide rate normalized: max -> {homicide_rate_n.max()}, min -> {homicide_rate_n.min()}, avg -> {homicide_rate_n.mean()}")

64.2 84.4
0.2 26.8
life expectancy normalized: max -> 1.0, min -> 0.0, avg -> 0.7959688826025457
homicide rate normalized: max -> 1.0, min -> 0.0, avg -> 0.11555674901539562